services:
  mongodb:
    image: mongo:6-jammy
    container_name: dfcom-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dfcom-challenge

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: dfcom-backend
  #   restart: unless-stopped
  #   ports:
  #     - '3333:3333'
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGODB_URI=${MONGODB_URI}
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: dfcom-frontend
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - backend
  #   environment:
  #     - VITE_API_URL=http://localhost:3000

volumes:
  mongodb_data:
