services:
  mongodb:
    image: mongo:6-jammy
    container_name: dfcom-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dfcom-challenge

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: dfcom-backend
  #   ports:
  #     - '3333:3333'
  #   expose:
  #     - 3333
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGODB_URI=${MONGODB_URI}

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: dfcom-frontend
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - backend
  #   environment:
  #     - BASE_URL=${BASE_URL}

volumes:
  mongodb_data:
